/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/dna`; params?: Router.UnknownInputParams; } | { pathname: `/engagement`; params?: Router.UnknownInputParams; } | { pathname: `/FileRoleActivityScreen`; params?: Router.UnknownInputParams; } | { pathname: `/gallery`; params?: Router.UnknownInputParams; } | { pathname: `/get-data`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/stories`; params?: Router.UnknownInputParams; } | { pathname: `/upload`; params?: Router.UnknownInputParams; } | { pathname: `/userlist`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/dna`; params?: Router.UnknownOutputParams; } | { pathname: `/engagement`; params?: Router.UnknownOutputParams; } | { pathname: `/FileRoleActivityScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/gallery`; params?: Router.UnknownOutputParams; } | { pathname: `/get-data`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/stories`; params?: Router.UnknownOutputParams; } | { pathname: `/upload`; params?: Router.UnknownOutputParams; } | { pathname: `/userlist`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/dna${`?${string}` | `#${string}` | ''}` | `/engagement${`?${string}` | `#${string}` | ''}` | `/FileRoleActivityScreen${`?${string}` | `#${string}` | ''}` | `/gallery${`?${string}` | `#${string}` | ''}` | `/get-data${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/stories${`?${string}` | `#${string}` | ''}` | `/upload${`?${string}` | `#${string}` | ''}` | `/userlist${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/dna`; params?: Router.UnknownInputParams; } | { pathname: `/engagement`; params?: Router.UnknownInputParams; } | { pathname: `/FileRoleActivityScreen`; params?: Router.UnknownInputParams; } | { pathname: `/gallery`; params?: Router.UnknownInputParams; } | { pathname: `/get-data`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/stories`; params?: Router.UnknownInputParams; } | { pathname: `/upload`; params?: Router.UnknownInputParams; } | { pathname: `/userlist`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
